nav:
  - CLI Access: cli
  - Block Storage: block
  - Compute: compute
  - Quota Management: quotas
  - Images: images
  - Identity: identity
  - Networking: networking
  - Containers: containers
  - Object Storage: object
  - Overriding Public Endpoints: public-endpoints.md
  - Service Overrides: service-overrides.md
  - Resouce and Project Lookups: resource-lookups.md
