nav:
  - Availability: api-status.md
  - SJC3:
    - "<img src='https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Frackerlabs%2Frs-flex-uptime%2Frefs%2Fheads%2Fmaster%2Fstatus.json'/>": https://status.api.sjc3.rackspacecloud.com
    - "<strong>Control Panel</strong>": https://skyline.api.sjc3.rackspacecloud.com
  - DFW3:
    - "<img src='https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fthe2hill%2Frs-flex-uptime-dfw%2Frefs%2Fheads%2Fmaster%2Fstatus.json'/>": https://status.api.dfw3.rackspacecloud.com
    - "<strong>Control Panel</strong>": https://skyline.api.dfw3.rackspacecloud.com
  - IAD3:
    - "<img src='https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fthe2hill%2Frs-flex-uptime-iad%2Frefs%2Fheads%2Fmaster%2Fstatus.json'/>": https://status.api.iad3.rackspacecloud.com
    - "<strong>Control Panel</strong>": https://skyline.api.iad3.rackspacecloud.com
