nav:
  - Welcome: index.md
  - Overview: overview
  - Design Guide: design
  - Deployment Guide: deployment
  - Operations Guide: operations
  - Cloud Onboarding: onboarding
  - Blog: https://blog.rackspacecloud.com/blog
  - OpenStack Flex: flex
