name: docs pages build and deployment

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "helm-chart-versions.yaml"
      - ".github/workflows/docs-pages.yaml"
      - "releasenotes/notes/**"
  pull_request:
    paths:
      - "docs/**"
      - "helm-chart-versions.yaml"
      - ".github/workflows/docs-pages.yaml"
      - "releasenotes/notes/**"
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json
      - run: ./docs/scripts/generate_product_matrix.sh
      - run: make -C docs build
      - uses: actions/upload-pages-artifact@main
        with:
          path: docs/public

  deploy:
    # depend on the docs being built
    needs: build

    # ensure we only run on commits to the main branch
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
